# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Commuter Buddy - CTA Version' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Commuter Buddy - CTA Version

  target 'Commuter Buddy - CTA VersionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Commuter Buddy - CTA VersionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless [
      'SwiftDate-iOS',
      'SwiftDate-macOS',
      'SwiftDate-tvOS'
    ].include? target.name

    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end

end

target 'Commuter Buddy Watch - CTA Version' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Commuter Buddy Watch - CTA Version

end

target 'Commuter Buddy Watch - CTA Version Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Commuter Buddy Watch - CTA Version Extension

end
